### ISSUE TITLE
paper 1.21.3 not  start 1.24.3

### ISSUE THREAD

**Issue by lindenes** [ThizThizzyDizzy/tree-feller#102]
```
curl --output treeFeller.jar https://github.com/ThizThizzyDizzy/tree-feller/releases/download/v1.24.3/TreeFeller-1.24.3.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
```
java -Xmx3072M -Xms1024M -jar paper.jar
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
[18:17:58 INFO]: [bootstrap] Running Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.5+9-LTS-239; Oracle Corporation null) on Linux 6.1.0-26-amd64 (amd64)
[18:17:58 INFO]: [bootstrap] Loading Paper 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) for Minecraft 1.21.3
[18:17:58 INFO]: [PluginInitializerManager] Initializing plugins...
[18:17:58 ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to open plugin jar plugins/treeFeller.jar
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
	at io.papermc.paper.pluginremap.PluginRemapper.waitForAll(PluginRemapper.java:410) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:206) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:42) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.Main.main(Main.java:123) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to open plugin jar plugins/treeFeller.jar
	at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:339) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	... 9 more
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs@21.0.5/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1320) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.5/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1541) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.5/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.5/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.5/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120) ~[jdk.zipfs:?]
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528) ~[?:?]
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:440) ~[?:?]
	at io.papermc.paper.pluginremap.PluginRemapper.remap(PluginRemapper.java:290) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.pluginremap.PluginRemapper.remapPlugin(PluginRemapper.java:266) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.pluginremap.PluginRemapper.rewritePluginDirectory(PluginRemapper.java:204) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	... 9 more
```

**Comment by ThizThizzyDizzy** [comment]
You have downloaded an empty file.

GitHub download links involve redirects, which `curl` does not follow by default. Use the `-L` option with `curl` to follow redirects, or download it via another method.

**Comment by lindenes** [comment]
thank you very much

ср, 18 дек. 2024 г. в 22:29, Thiz ***@***.***>:
