### ISSUE TITLE
NullPointer for Ores

### ISSUE THREAD

**Issue by martinambrus** [ThizThizzyDizzy/tree-feller#12]
When using TreeFeller with the fun facts / tips provided on plugin's CurseForge page, I get the following error in console (even though the plugin works fine):

``` [14:17:31 ERROR]: Could not pass event BlockBreakEvent to TreeFeller v1.11
java.lang.NullPointerException: null
at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:245) ~[?:?]
at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:57) ~[?:?]
at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:54) ~[?:?]
at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:51) ~[?:?]
at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:48) ~[?:?]
at com.thizthizzydizzy.treefeller.BlockBreak.onBlockBreak(BlockBreak.java:45) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-112]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-112]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-112]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:313) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:272) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:240) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1320) ~[?:git-Paper-112]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-112]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

This is using the provided example setup on plugin's website:
- [COAL_ORE, COAL_ORE, {required-leaves: 0, leaf-range: 0, max-height: 256}]
- {type: IRON_PICKAXE, allowed-trees: ORE}

**Comment by ThizThizzyDizzy** [comment]
Fixed in 1.12
