### ISSUE TITLE
Bug with MMOCore compatibility

### ISSUE THREAD

**Issue by Frank-xy** [ThizThizzyDizzy/tree-feller#34]
Environment:
Paper Spigot 1.16.5
MMOCore 1.7.1
Tree Feller 1.16.2

log when trying to cut down a "debug verified" tree:
**_[13:11:35 WARN]: [TreeFeller] Task #188604 for TreeFeller v1.16.2 generated an exception
java.lang.NoSuchMethodError: 'net.Indyuce.mmocore.api.player.PlayerData net.Indyuce.mmocore.api.player.PlayerData.get(org.bukkit.entity.Player)'
        at com.thizthizzydizzy.treefeller.compat.MMOCoreCompat.breakBlock(MMOCoreCompat.java:253) ~[?:?]
        at com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.breakBlock(TreeFellerCompat.java:31) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:848) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.access$200(TreeFeller.java:41) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller$1.run(TreeFeller.java:197) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-779]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-779]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-779]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-779]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-779]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-779]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-779]
        at java.lang.Thread.run(Thread.java:829) [?:?]_**

**Comment by ThizThizzyDizzy** [comment]
Looks like the MMOCore API may have changed; Can you confirm MMOCore is installed and functional?

**Comment by Frank-xy** [comment]
> Looks like the MMOCore API may have changed; Can you confirm MMOCore is installed and functional?

Yes, it works well. And all other plugins with MMOCore compatibility(Using getPlayerData API) work as well.
