### ISSUE TITLE
Error on 1.19.4

### ISSUE THREAD

**Issue by SlimeDog** [ThizThizzyDizzy/tree-feller#60]
Spigot 1.19.4-3686 or Paper 1.19.4-462
TreeFeller 1.21.2

No errors on server start-up (ie., TreeFeller load and enable)
```
[14:12:21] [Server thread/INFO]: [TreeFeller] Loading TreeFeller v1.21.2
[14:13:02] [Server thread/INFO]: [TreeFeller] Enabling TreeFeller v1.21.2
[14:13:02] [Server thread/INFO]: [TreeFeller] TreeFeller has been enabled! (Version 1.21.2) by ThizThizzyDizzy
```

When I cut a tree (spruce, with a netherite_axe), the leaves disappear (as expected), but the trunk falls straight down, closing the cut (unexpected)

![Screen Shot 2023-03-19 at 4 01 07 PM](https://user-images.githubusercontent.com/17748923/226215190-da0eef5f-124e-42c8-be8d-06b31b1fad2b.png)

Debug reports no errors, and success

![Screen Shot 2023-03-19 at 4 04 49 PM](https://user-images.githubusercontent.com/17748923/226215365-51a6641d-bf90-47a9-9c8b-e047edfd514b.png)

but an error is logged at the console
```
[16:00:45 WARN]: [TreeFeller] Task #27598 for TreeFeller v1.21.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.thizthizzydizzy.vanillify.Vanillify
        at com.thizthizzydizzy.treefeller.FellBehavior.processFallBehavior(FellBehavior.java:159) ~[TreeFeller-1.21.2.jar:?]
        at com.thizthizzydizzy.treefeller.FellBehavior.access$100(FellBehavior.java:11) ~[TreeFeller-1.21.2.jar:?]
        at com.thizthizzydizzy.treefeller.FellBehavior$5.breakBlock(FellBehavior.java:58) ~[TreeFeller-1.21.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:950) ~[TreeFeller-1.21.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.access$200(TreeFeller.java:55) ~[TreeFeller-1.21.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller$1.run(TreeFeller.java:255) ~[TreeFeller-1.21.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[paper-1.19.4.jar:git-Paper-462]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-462]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Your server version isn't supported in Vanillify! [in thread "Server thread"]   
        at com.thizthizzydizzy.vanillify.version.VersionMatcher.lambda$match$1(VersionMatcher.java:43) ~[TreeFeller-1.21.2.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.thizthizzydizzy.vanillify.version.VersionMatcher.match(VersionMatcher.java:43) ~[TreeFeller-1.21.2.jar:?]
        at com.thizthizzydizzy.vanillify.Vanillify.<clinit>(Vanillify.java:7) ~[TreeFeller-1.21.2.jar:?]
        ... 14 more
```

Configuration sans comments
```
startup-logs: false
default-enabled: true
scan-distance: 256
leaf-detect-range: 6
leaf-break-range: 6
required-logs: 4
required-leaves: 10
max-logs: 250
max-height: 5
allow-partial: false
player-leaves: false
diagonal-leaves: false
ignore-leaf-data: false
require-cross-section: true
force-distance-check: false
banned-logs: 
banned-leaves: 
max-horizontal-trunk-pillar-length: 6
max-trunks: 1
cutting-animation: true
anim-delay: 1
replant-saplings: false
use-inventory-saplings: false
spawn-saplings: 0
sapling-timeout: 50
grass: 
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    - ROOTED_DIRT
root-distance: 6
log-behavior: FALL_HURT
leaf-behavior: BREAK
fall-hurt-amount: 2.0
fall-hurt-max: 40
directional-fall-behavior: AWAY
overridables: 
    - AIR
    - CAVE_AIR
    - FERN
    - GRASS
    - LARGE_FERN
    - SEAGRASS
    - TALL_GRASS
    - TALL_SEAGRASS
    - WATER
lock-fall-cardinal: false
directional-fall-velocity: 0.45
vertical-fall-velocity: 0.05
explosive-fall-velocity: 0.0
random-fall-velocity: 0.15
respect-unbreaking: true
respect-unbreakable: true
damage-mult: 1.0
stacked-tools: false
leaf-fortune: true
leaf-silk-touch: false
log-fortune: true
log-silk-touch: true
leave-stump: true
rotate-logs: true
drop-conversions: 
    OAK_WOOD: OAK_LOG
    SPRUCE_WOOD: SPRUCE_LOG
    BIRCH_WOOD: BIRCH_LOG
    JUNGLE_WOOD: JUNGLE_LOG
    ACACIA_WOOD: ACACIA_LOG
    DARK_OAK_WOOD: DARK_OAK_LOG
    CRIMSON_HYPHAE: CRIMSON_STEM
    WARPED_HYPHAE: WARPED_STEM
block-conversions: 
leaf-drop-chance: 0.0
log-drop-chance: 1.0
global-effects:
    - sawdust
consumed-food-base: 0.0
consumed-food-logs: 0.0
consumed-food-leaves: 0.0
consumed-health-base: 0.0
consumed-health-logs: 0.0
consumed-health-leaves: 0.0
required-enchantments:
banned-enchantments:
min-durability:
max-durability:
min-durability-percent:
max-durability-percent:
prevent-breakage: false
required-lore:
required-name:
required-permissions:
min-time:
max-time:
min-phase:
max-phase:
min-food:
max-food:
min-health:
max-health:
custom-model-data:
enable-adventure: false
enable-survival: true
enable-creative: false
with-sneak: false
without-sneak: true
worlds:
   - world_skyblock
   - world_skyblock_nether
   - world_skyblock_the_end
world-blacklist: true
cooldown:
cascade: false
parallel-cascade-limit: 1
cascade-check-limit: 64
mmocore-trunk-xp: 
   - global: 1
mmocore-leaves-xp: 
   - global: 0
mmocore-required-profession-level:
mmocore-tree-xp: 
   - global: 0
mmocore-emulate-regen: false
compatibility-mmocore: false
compatibility-jobs: false
mcmmo-double-drops: true
compatibility-mcmmo: false
compatibility-mcmmo: false
compatibility-coreprotect: true
compatibility-worldguard: true
compatibility-griefprevention: false
compatibility-towny: false
oreregenerator-regen-delay: 1200
compatibility-oreregenerator: false
compatibility-drop2inventory: false
ecoskills-trunk-woodcutting-xp: 1.0
ecoskills-trunk-mining-xp: 0.0
ecoskills-leaf-woodcutting-xp: 0.0
ecoskills-leaf-mining-xp: 0.0
ecoskills-apply-modifiers: false
ecojobs-trunk-xp:
ecojobs-leaf-xp:
ecojobs-apply-multipliers: true
compatibility-ecoskills: false
compatibility-logblock: false
compatibility-lands: true
compatibility-placeholderapi: true
compatibility-saberfactions: false
aureliumskills-trunk-xp: 
   - foraging: 1
aureliumskills-leaves-xp: 
   - foraging: 0
aureliumskills-apply-modifiers: false
compatibility-aureliumskills: false
compatibility-blockregen: false
tools:
    - { type: WOODEN_AXE, required-permissions: [treefeller.wooden_axe] }
    - { type: STONE_AXE, required-permissions: [treefeller.stone_axe] }
    - { type: IRON_AXE, required-permissions: [treefeller.iron_axe] }
    - { type: GOLDEN_AXE, required-permissions: [treefeller.golden_axe] }
    - { type: DIAMOND_AXE, required-permissions: [treefeller.diamond_axe] }
    - { type: NETHERITE_AXE, required-permissions: [treefeller.netherite_axe] }
    - { type: AIR, required-permissions: [treefeller.air], damageMult: 0.0 }
trees:
    - [[OAK_LOG, OAK_WOOD], OAK_LEAVES, {sapling: OAK_SAPLING, max-saplings: 1}]
    - [[BIRCH_LOG, BIRCH_WOOD], BIRCH_LEAVES, {sapling: BIRCH_SAPLING, max-saplings: 1}]
    - [[SPRUCE_LOG, SPRUCE_WOOD], SPRUCE_LEAVES, {sapling: SPRUCE_SAPLING, max-saplings: 4}]
    - [[JUNGLE_LOG, JUNGLE_WOOD], JUNGLE_LEAVES, {sapling: JUNGLE_SAPLING, max-saplings: 4}]
    - [[DARK_OAK_LOG, DARK_OAK_WOOD], DARK_OAK_LEAVES, {sapling: DARK_OAK_SAPLING, max-saplings: 4}]
    - [[ACACIA_LOG, ACACIA_WOOD], ACACIA_LEAVES, {sapling: ACACIA_SAPLING, max-saplings: 1}]
    - [[OAK_LOG, OAK_WOOD], [AZALEA_LEAVES, FLOWERING_AZALEA_LEAVES], {sapling: [AZALEA, FLOWERING_AZALEA], max-saplings: 1, diagonal-leaves: true}]
    - [[MANGROVE_LOG, MANGROVE_WOOD], [MANGROVE_ROOTS, MANGROVE_LEAVES], {roots: [MANGROVE_ROOTS], sapling: [MANGROVE_PROPAGULE], max-saplings: 1, max-trunks: 16, max-horizontal-trunk-pillar-length: 16, leaf-detect-range: 16, leaf-break-range: 16, required-logs: 3, root-distance: 16, diagonal-leaves: true}]
    - [[CRIMSON_STEM, CRIMSON_HYPHAE], [NETHER_WART_BLOCK, SHROOMLIGHT], {sapling: CRIMSON_FUNGUS, max-saplings: 1, grass: [CRIMSON_NYLIUM], diagonal-leaves: true, leaf-detect-range: 8, leaf-break-range: 8}]
    - [[WARPED_STEM, WARPED_HYPHAE], [WARPED_WART_BLOCK, SHROOMLIGHT], {sapling: WARPED_FUNGUS, max-saplings: 1, grass: [WARPED_NYLIUM], diagonal-leaves: true, leaf-detect-range: 8, leaf-break-range: 8}]
effects:
    - {name: sawdust, chance: 1.0, location: logs, type: particle, particle: poof, dx: 0.5, dy: 0.5, dz: 0.5, speed: .01, count: 10}
 ```

**Comment by SlimeDog** [comment]
Thanks. TreeFeller is number 46 (of 162 plugins that I test) that has been explicitly updated to support 1.19.4. Although there are some remaining, most of the rest support 1.19.4 without change.

> Although it seems that bukkit 1.19.4 hasn't been properly recognized by most things yet; (spigot & curseforge both show 1.19.3 as latest)

Pay no attention to `latest`.
- Spigot support was nearly immediate, on 2023-03-14: [https://hub.spigotmc.org/versions/1.19.4.json](https://hub.spigotmc.org/versions/1.19.4.json)
- Paper support followed a few days later: [https://papermc.io/downloads](https://papermc.io/downloads)

**Comment by SlimeDog** [comment]
TreeFeller 1.2.1

No errors on start-up. However, felling does not behave as expected. Per configuration above, I expect logs to fall away from me. Instead, I get a gravitational drop, with the single cut log falling away.

![Screen Shot 2023-03-21 at 7 43 54 AM](https://user-images.githubusercontent.com/17748923/226644322-7329d0cb-6e63-4ab8-8738-f253c4d623b4.png)

![Screen Shot 2023-03-21 at 7 45 08 AM](https://user-images.githubusercontent.com/17748923/226644368-5eaf49d6-9215-4be8-86f5-4190ba7786b1.png)

**Comment by ThizThizzyDizzy** [comment]
hmm; I tested your configuration earlier;; I noticed this happening when destroying the bottom block, but attributed it to just falling block wierdness

**Comment by SlimeDog** [comment]
Previously with that configuration, the entire stack (above the cut) fell off in all directions, leaving only the stump.

**Comment by ThizThizzyDizzy** [comment]
hmm, I'll reopen the issue, but I won't have much time to look into it until next week;

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
Thanks for looking.

Note: CraftBukkit <> Spigot, although perhaps functionally equivalent for TreeFeller.

**Comment by ThizThizzyDizzy** [comment]
Summary of my findings so far:
The issue you describe, (one block flying forwards, others falling straight down) happens on paper, but not on craftbukkit; disabling cutting-animation seems to fix this entirely (I'll see if I can add a delay to bypass this, although it may not look as nice)

The issue I had seems to be entirely separate, affecting craftbukkit (but not paper) and is not affected by cutting-animation at all
This is where the tree basically just hops over one block (and some of the blocks turn sideways) but stays upright
(Most notable when cutting down oak trees in cardinal directions)

> Note: CraftBukkit <> Spigot, although perhaps functionally equivalent for TreeFeller.
I am aware; but I personally don't like spigot/etc, so I tend to test everything with craftbukkit, as it's generally been a safe assumption that if it works on craftbukkit, it *should* work on the others as well

**Comment by ThizThizzyDizzy** [comment]
I did also find an oddity where the sideways velocity was dependent on your distance from the tree (it was using a normalized 3D vector rather than X/Z)
Fixing that didn't make any significant difference in the issue at hand though

**Comment by ThizThizzyDizzy** [comment]
Fixed with a new option `fall-delay`; which adds a delay between removing a block and spawning the falling block (Set this to 1)
I think the issue was caused by the blocks colliding with the one above it before it disappears
This doesn't seem to fix my craftbukkit issue though; craftbukkit seems to just have weirder collision handling

**Comment by ThizThizzyDizzy** [comment]
That sounds like the issue I was having with craftbukkit (lowest trunk block and all)
I never had this on paper, but I wasn't able to fix it in craftbukkit either
Since it's a product of the falling block collisions, there's nothing more I can think of to fix on my end; All I can recommend is playing with the velocities a bit more to try and get it a bit more reliable
(`fall-delay` is in ticks, yes)

**Comment by SlimeDog** [comment]
On Spigot/CraftBukkit, the stacking issue seems to happen more frequently on the cardinal points.

**Comment by ThizThizzyDizzy** [comment]
I've noticed that as well; It seems backwards, since the cardinal directions theoretically would have the *least* chance of the blocks hitting each other due to a shorter distance to the edge of the block
