### ISSUE TITLE
1.20.2 Purpur; Spams Console When A Tree Is Cut

### ISSUE THREAD

**Issue by GitNuck** [ThizThizzyDizzy/tree-feller#80]
Plugin still works but spams the console with warnings.

`[18:35:15 WARN]: [TreeFeller] Task #55864 for TreeFeller v1.22.1 generated an exception
java.lang.ExceptionInInitializerError: null
	at com.thizthizzydizzy.treefeller.FellBehavior.processNaturalFallBehavior(FellBehavior.java:277) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.treefeller.FellBehavior.processDelayedNaturalFallBehavior(FellBehavior.java:262) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.treefeller.FellBehavior.access$200(FellBehavior.java:14) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.treefeller.FellBehavior$13.breakBlock(FellBehavior.java:157) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:977) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.treefeller.TreeFeller.access$200(TreeFeller.java:57) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.treefeller.TreeFeller$1.run(TreeFeller.java:265) ~[TreeFeller-1.22.1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2077]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: [VANILLIFY] Unsupported server version: 1_20_R2
	at com.thizthizzydizzy.vanillify.version.VersionMatcher.lambda$match$1(VersionMatcher.java:45) ~[TreeFeller-1.22.1.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.thizthizzydizzy.vanillify.version.VersionMatcher.match(VersionMatcher.java:45) ~[TreeFeller-1.22.1.jar:?]
	at com.thizthizzydizzy.vanillify.Vanillify.<clinit>(Vanillify.java:7) ~[TreeFeller-1.22.1.jar:?]
	... 15 more`

**Comment by ThizThizzyDizzy** [comment]
Updating Vanillify for 1.20.2, sorry it took so long

**Comment by GitNuck** [comment]
> Updating Vanillify for 1.20.2, sorry it took so long

No apologies needed, I'm glad you made this plugin and showed up lol!  It was just spam in the console, everything seemed to be working fine.  Thank you for your hard work and time :)
