### ISSUE TITLE
Check ore regenerator compatibility

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/tree-feller#86]
https://discord.com/channels/538800846251753483/538802868271185931/1218301377609072640
[20:52:48 WARN]: [TreeFeller] Task #680997 for TreeFeller v1.22.2 generated an exception
java.lang.NoClassDefFoundError: dev/mrshawn/oreregenerator/api/utils/RegenUtils
        at com.thizthizzydizzy.treefeller.compat.OreRegeneratorCompat.breakBlock(OreRegeneratorCompat.java:57) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.breakBlock(TreeFellerCompat.java:55) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:975) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.access$200(TreeFeller.java:57) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller$1.run(TreeFeller.java:262) ~[TreeFeller-1.22.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run() ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat() ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-21]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.mrshawn.oreregenerator.api.utils.RegenUtils
        ... 13 more

**Comment by ThizThizzyDizzy** [comment]
Can't fix this myself as this is a premium plugin with no public source code or API.
