### ISSUE TITLE
Check MCMMO compatibility

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [ThizThizzyDizzy/tree-feller#90]
https://discord.com/channels/538800846251753483/538802868271185931/1226300025223643259
[00:34:28 ERROR]: Could not pass event BlockBreakEvent to TreeFeller v1.22.3
java.lang.NoClassDefFoundError: com/gmail/nossr50/util/random/RandomChanceUtil
        at com.thizthizzydizzy.treefeller.compat.McMMOCompat.breakBlock(McMMOCompat.java:38) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.breakBlock(TreeFellerCompat.java:55) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:975) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:295) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:97) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:94) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:91) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:88) ~[TreeFeller-1.22.3.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFellerEventListener.onBlockBreak(TreeFellerEventListener.java:26) ~[TreeFeller-1.22.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1183.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-473]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-473]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-473]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1847) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-473]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-473]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.util.random.RandomChanceUtil
        ... 36 more

**Comment by tticehurst** [comment]
FIle no longer exists?
![image](https://github.com/ThizThizzyDizzy/tree-feller/assets/46826453/0c5d244a-5e5a-4272-9060-0b94d969087a)

**Comment by tticehurst** [comment]
Replace with
`isSkillRNGSuccessful`
or
`getSkillProbability`
?

**Comment by ThizThizzyDizzy** [comment]
https://discord.com/channels/538800846251753483/538802868271185931/1228514988985946112

**Comment by tticehurst** [comment]
Can't open that link

**Comment by tticehurst** [comment]
any updates?

**Comment by ThizThizzyDizzy** [comment]
not yet; finals week this week. I'll make a patch for this next week-ish

**Comment by tticehurst** [comment]
Good luck with the finals

**Comment by ThizThizzyDizzy** [comment]
Confirmed fixed in v1.23.0 (releasing soon)
