### ISSUE TITLE
Fix Prism Compatibility 

### ISSUE THREAD

**Issue by sixtysixx** [ThizThizzyDizzy/tree-feller#96]
Treefeller isnt starting when prism is installed. Im using PufferFish+ ~ 1.20.4

Paste can be found @ https://paste.gg/p/anonymous/89d0c63d4de442d0b611bda5a2cae273

Thank you.

- Six

(psst, I often dont check GitHub, Contact me on [one of my socials](https://e-z.bio/sixtysxx) If I dont seem to acknowledge any updates, patches, or fixes.)

**Comment by ThizThizzyDizzy** [comment]
Looks like the packages changed, hmm
In the meantime, you can disable `compatibility-prism` in the config to bypass the crash

**Comment by sixtysixx** [comment]
Had to edit the jar as it wasnt generating the config files, works now!

**Comment by ThizThizzyDizzy** [comment]
paste.gg is broken right now, so I can't see what the error was; I guess I'll look into this another time

**Comment by ThizThizzyDizzy** [comment]
https://mclo.gs/AnGFmHr
Out of the wild, here's another TreeFeller prism error.
I'll also paste the error here just in case that site dies too. (paste.gg is *still* broken)

```
[15:14:43] [Server thread/INFO]: [TreeFeller] TreeFeller has been enabled! (Version 1.25.1) by ThizThizzyDizzy
[15:14:43] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
[15:14:43] [Server thread/ERROR]: Error occurred while enabling TreeFeller v1.25.1 (Is it up to date?)
java.lang.NoClassDefFoundError: me/botsko/prism/Prism
	at TreeFeller-1.25.1.jar/com.thizthizzydizzy.treefeller.compat.PrismCompat.init(PrismCompat.java:26) ~[TreeFeller-1.25.1.jar:?]
	at TreeFeller-1.25.1.jar/com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.init(TreeFellerCompat.java:46) ~[TreeFeller-1.25.1.jar:?]
	at TreeFeller-1.25.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.reload(TreeFeller.java:804) ~[TreeFeller-1.25.1.jar:?]
	at TreeFeller-1.25.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.reload(TreeFeller.java:737) ~[TreeFeller-1.25.1.jar:?]
	at TreeFeller-1.25.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.onEnable(TreeFeller.java:649) ~[TreeFeller-1.25.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:284) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:656) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:605) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-100-86c6308]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.botsko.prism.Prism
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 17 more
[15:14:43] [Server thread/INFO]: [TreeFeller] Disabling TreeFeller v1.25.1
[15:14:43] [Server thread/INFO]: [TreeFeller] TreeFeller has been disabled! (Version 1.25.1) by ThizThizzyDizzy
```

**Comment by sixtysixx** [comment]
Seems paste.gg is back up, same error you've gotten. However, I was using 1.24.0 at the time; if that matters.
Incase paste.gg goes back down again:

Wayback Machine - https://web.archive.org/web/20250401032807/https://paste.gg/p/anonymous/89d0c63d4de442d0b611bda5a2cae273/files/ab20386e3f8a4f9ba7cec631c5e99170/raw

**Comment by ThizThizzyDizzy** [comment]
Sounds like there's separate versions for 1.16 and 1.17+, need to support both

>>> 
the older one: https://www.spigotmc.org/resources/prism.75166/
the newer one: https://www.spigotmc.org/resources/prism.99397/

**Comment by ThizThizzyDizzy** [comment]
of course, by the time I get to this, there's now yet another. (Prism 4)
https://modrinth.com/plugin/prism

**Comment by sixtysixx** [comment]
> of course, by the time I get to this, there's now yet another. (Prism 4) https://modrinth.com/plugin/prism

Classic. I appreciate your effort.
