### ISSUE TITLE
Auraskill Compatibility Error

### ISSUE THREAD

**Issue by Vrtox** [ThizThizzyDizzy/tree-feller#98]
Hello, 

I have an issue with Treefeller and Auraskills. The Trees are still getting felled but the integration with AuraSkills just doesnt seem to be working. You dont get Foraging XP. If you need more information feel free to ask.
Whenever I fell a tree it gives the following error message:
```
[14:38:05 ERROR]: [TreeFeller] Exception in AuraSkills compatibility!
java.lang.IllegalArgumentException: Invalid NamespacedId: foraging
        at AuraSkills-2.2.4.jar/dev.aurelium.auraskills.api.registry.NamespacedId.fromString(NamespacedId.java:69) ~[AuraSkills-2.2.4.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.compat.AuraSkillsCompat.breakBlock(AuraSkillsCompat.java:275) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.breakBlock(TreeFellerCompat.java:57) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:975) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:295) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:97) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:94) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:91) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:88) ~[TreeFeller-1.24.2.jar:?]
        at TreeFeller-1.24.2.jar/com.thizthizzydizzy.treefeller.TreeFellerEventListener.onBlockBreak(TreeFellerEventListener.java:26) ~[TreeFeller-1.24.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor220.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-128-d348cb8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1856) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I use Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS; Eclipse Adoptium Temurin-21.0.3+9) on Linux 5.4.0-198-generic
with Paper 1.21.1 Build #128 (latest)

and the following plugins
- ProtocolLib v5.3.0
- vane-core v1.15.0
- AuraSkills v2.2.4
- vane-regions v1.15.0
- OpenShulker v1.3.0
- vane-bedtime v1.15.0
- Waypoints v4.5.3
- AxGraves v1.14.6
- ExtraRecipes v1.4.0
- HomesPlugin v1.4
- Hammer v1.0.0
- vane-admin v1.15.0
- Networks v3.0.4
- vane-enchantments v1.15.0
- vane-permissions v1.15.0
- DatapackLoader v1.4.1
- TreeFeller v1.24.2
- vane-trifles v1.15.0
- Chunky v1.4.10
- AshLib v1.0
- BackpackPlus v1.4.4
- villagerinfinitetrading v1.0
- VillagerOptimizer v1.6.2
- AutoTool v1.2
- vane-portals v1.15.0
- ClickVillagers v0.5.1

Thanks,
Vertox

**Comment by ThizThizzyDizzy** [comment]
The defaults in the TreeFeller config are invalid; aura skills is namespaced now
Update the aura skills referenced in the config to say `"auraskills:foraging"` instead of `foraging`, for example

**Comment by Vrtox** [comment]
Thanks for the quick response! it didnt work with `auraskills:foraging` but then I checked the auraskills skills.yml and it worked with `auraskills/foraging`

**Comment by ArgentCrow** [comment]
I'm having this same issue now

`[13:38:47] [Server thread/ERROR]: [TreeFeller] Exception in AuraSkills compatibility!
java.lang.IllegalArgumentException: Invalid NamespacedId: foraging
        at dev.aurelium.auraskills.api.registry.NamespacedId.fromString(NamespacedId.java:80) ~[?:?]
        at com.thizthizzydizzy.treefeller.compat.AuraSkillsCompat.breakBlock(AuraSkillsCompat.java:275) ~[?:?]
        at com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.breakBlock(TreeFellerCompat.java:57) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:975) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:295) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:97) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:94) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:91) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:88) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFellerEventListener.onBlockBreak(TreeFellerEventListener.java:26) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:367) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:326) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:294) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1592) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:50) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:164) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1319) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:210) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:138) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1298) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1291) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:147) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1248) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.x_(MinecraftServer.java:1258) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1101) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`
        
Paper 1.21.4
following plugins 

- Bookshelf 3.1.12
- Extra Recipes 1.4.0
- AuraSkills 2.2.7
- Tree Feller 1.25.0

I've tried changing foraging in the config to auraskills:foraging and auraskills/foraging. Neither seems to make any difference
![1](https://github.com/user-attachments/assets/61d5b189-3b1d-48ec-9daa-3c93dde47f62)

**Comment by ThizThizzyDizzy** [comment]
`auraskills/foraging` should work fine; `:` won't work due to YAML formatting issues.

**Comment by ArgentCrow** [comment]
I tried both, neither is working

**Comment by ArgentCrow** [comment]
![image](https://github.com/user-attachments/assets/9fdba3f3-7793-4757-a051-79657c90e8a7)
`[14:04:15] [Server thread/ERROR]: [TreeFeller] Exception in AuraSkills compatibility!
java.lang.IllegalArgumentException: Invalid NamespacedId: foraging
        at dev.aurelium.auraskills.api.registry.NamespacedId.fromString(NamespacedId.java:80) ~[?:?]
        at com.thizthizzydizzy.treefeller.compat.AuraSkillsCompat.breakBlock(AuraSkillsCompat.java:275) ~[?:?]
        at com.thizthizzydizzy.treefeller.compat.TreeFellerCompat.breakBlock(TreeFellerCompat.java:57) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:975) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:295) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:97) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:94) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:91) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:88) ~[?:?]
        at com.thizthizzydizzy.treefeller.TreeFellerEventListener.onBlockBreak(TreeFellerEventListener.java:26) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:367) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:326) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:294) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1592) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:50) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:164) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1319) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:210) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:138) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1298) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1291) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:147) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1248) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.x_(MinecraftServer.java:1258) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1101) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4423-Spigot-aa7842e-c16b696]
        at java.base/java.lang.Thread.run(Thread.java:1583) `[?:?]`
Still the same problem when using auraskills/foraging

**Comment by ThizThizzyDizzy** [comment]
this issue may be caused by a malformed config, causing it to revert to default values. Check startup/reload logs for errors loading the config.
I am also fixing the default values now so that this workaround will be unnecessary (8ed58c94)
